// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505225036_PremiumWorkouts")]
    partial class PremiumWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Features.AdaptivePlanning.AdaptiveRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppliesFromDate")
                        .HasColumnType("date");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)");

                    b.Property<Guid?>("SourceReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceReportId");

                    b.HasIndex("UserId", "Status", "ExpiresAtUtc");

                    b.ToTable("AdaptiveRecommendations");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.CoachSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdaptiveNutritionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AdaptiveTrainingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("AggressivenessLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoApplyLowRiskSuggestions")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferredReportDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CoachSettings");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.ExerciseTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxReps")
                        .HasColumnType("integer");

                    b.Property<int>("MinReps")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressionModel")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("ExerciseTargets");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.NutritionTargetsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fat")
                        .HasColumnType("integer");

                    b.Property<int>("Protein")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("UserId", "ActiveFrom");

                    b.ToTable("NutritionTargetsHistory");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationExerciseTargetChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentTargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CurrentTargetWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxReps")
                        .HasColumnType("integer");

                    b.Property<int?>("MinReps")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressionModel")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SuggestedTargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SuggestedTargetWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.ToTable("RecommendationExerciseTargetChanges");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationNutritionChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentCarbs")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentFat")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentProtein")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SuggestedCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("SuggestedCarbs")
                        .HasColumnType("integer");

                    b.Property<int?>("SuggestedFat")
                        .HasColumnType("integer");

                    b.Property<int?>("SuggestedProtein")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.ToTable("RecommendationNutritionChanges");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationRecoveryAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FocusMusclesText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendedSession")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RestMusclesText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.ToTable("RecommendationRecoveryActions");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationTargetDateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CurrentTargetDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentWeeklyPaceKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SuggestedTargetDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("SuggestedWeeklyPaceKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.ToTable("RecommendationTargetDateChanges");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart", "WeekEnd", "AlgorithmVersion")
                        .IsUnique();

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportMuscleBalanceSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Sets")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<double>("VolumeKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId", "Muscle")
                        .IsUnique();

                    b.ToTable("WeeklyReportMuscleBalanceSummaries");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportNextWeekAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId", "SortOrder");

                    b.ToTable("WeeklyReportNextWeekActions");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportNutritionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageCarbs")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageFat")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageProtein")
                        .HasColumnType("integer");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LoggedDays")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCarbs")
                        .HasColumnType("integer");

                    b.Property<int>("TargetFat")
                        .HasColumnType("integer");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId")
                        .IsUnique();

                    b.ToTable("WeeklyReportNutritionSummaries");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportRecoverySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IntensityRecommendation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReadyMusclesText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("RecommendedNextSession")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RestMusclesText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId")
                        .IsUnique();

                    b.ToTable("WeeklyReportRecoverySummaries");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportTrainingSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BestProgressExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("BestProgressText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("CompletedWorkouts")
                        .HasColumnType("integer");

                    b.Property<int>("ExercisesDecreased")
                        .HasColumnType("integer");

                    b.Property<int>("ExercisesImproved")
                        .HasColumnType("integer");

                    b.Property<int>("ExercisesMaintained")
                        .HasColumnType("integer");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer");

                    b.Property<double>("TotalVolumeKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId")
                        .IsUnique();

                    b.ToTable("WeeklyReportTrainingSummaries");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportWeightSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("EndTrendWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("EstimatedGoalDate")
                        .HasColumnType("date");

                    b.Property<double?>("ExpectedWeeklyChangeKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("StartTrendWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<double?>("WeeklyChangeKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeightLogsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId")
                        .IsUnique();

                    b.ToTable("WeeklyReportWeightSummaries");
                });

            modelBuilder.Entity("backend.Features.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CreatedByUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUsedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastUsedByUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SessionFamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("SessionFamilyId", "RevokedAtUtc");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("backend.Features.Food.ComposedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsFavorite");

                    b.HasIndex("UserId", "UpdatedUtc");

                    b.ToTable("ComposedMeals");
                });

            modelBuilder.Entity("backend.Features.Food.ComposedMealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<Guid>("ComposedMealId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fats")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Proteins")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComposedMealId", "SortOrder");

                    b.ToTable("ComposedMealIngredients");
                });

            modelBuilder.Entity("backend.Features.Food.FoodLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<int>("Fats")
                        .HasColumnType("integer");

                    b.Property<int>("Proteins")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceComposedMealId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SourceServings")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SourceComposedMealId");

                    b.HasIndex("UserId", "TimestampUtc");

                    b.ToTable("FoodLogs");
                });

            modelBuilder.Entity("backend.Features.Training.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("DefaultProgressionStepKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsBodyweight")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompound")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIsolation")
                        .HasColumnType("boolean");

                    b.Property<string>("Muscle")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecificMuscleGroups")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("backend.Features.Training.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Muscle", "Role")
                        .IsUnique();

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutPrograms.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.SetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<double?>("Rir")
                        .HasColumnType("double precision");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SetType")
                        .HasColumnType("text");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorkoutExerciseLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseLogId");

                    b.ToTable("SetLogs");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseLogs");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmissionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TotalReps")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSets")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalVolume")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkoutProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutProgramId");

                    b.HasIndex("UserId", "ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.HasIndex("UserId", "SubmissionHash")
                        .IsUnique()
                        .HasFilter("\"SubmissionHash\" IS NOT NULL");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("backend.Features.Training.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayLabel")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkoutProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("backend.Features.Training.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "Order");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("backend.Features.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Features.Users.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CalorieGoal")
                        .HasColumnType("integer");

                    b.Property<int>("CarbGoal")
                        .HasColumnType("integer");

                    b.Property<int>("FatGoal")
                        .HasColumnType("integer");

                    b.Property<string>("FoodCoachExcludedDateKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("HasCompletedRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasDismissedRegistrationOnboarding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("HomeProgressCirclesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeSectionOrderJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("nb");

                    b.Property<int>("MuscleFilter")
                        .HasColumnType("integer");

                    b.Property<int>("ProteinGoal")
                        .HasColumnType("integer");

                    b.Property<string>("RecoveryMapHiddenMusclesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowOnlyCustomTrainingContent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseFoodCoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("UseWorkoutCoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeightDirection")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightGoalKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("WeightGoalTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("backend.Features.Weight.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.AdaptiveRecommendation", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "SourceReport")
                        .WithMany("Recommendations")
                        .HasForeignKey("SourceReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.ExerciseTarget", b =>
                {
                    b.HasOne("backend.Features.Training.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.NutritionTargetsHistory", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.AdaptiveRecommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationExerciseTargetChange", b =>
                {
                    b.HasOne("backend.Features.Training.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Features.AdaptivePlanning.AdaptiveRecommendation", "Recommendation")
                        .WithOne("ExerciseTargetChange")
                        .HasForeignKey("backend.Features.AdaptivePlanning.RecommendationExerciseTargetChange", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationNutritionChange", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.AdaptiveRecommendation", "Recommendation")
                        .WithOne("NutritionChange")
                        .HasForeignKey("backend.Features.AdaptivePlanning.RecommendationNutritionChange", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationRecoveryAction", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.AdaptiveRecommendation", "Recommendation")
                        .WithOne("RecoveryAction")
                        .HasForeignKey("backend.Features.AdaptivePlanning.RecommendationRecoveryAction", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.RecommendationTargetDateChange", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.AdaptiveRecommendation", "Recommendation")
                        .WithOne("TargetDateChange")
                        .HasForeignKey("backend.Features.AdaptivePlanning.RecommendationTargetDateChange", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportMuscleBalanceSummary", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithMany("MuscleBalance")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportNextWeekAction", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithMany("NextWeekActions")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportNutritionSummary", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithOne("NutritionSummary")
                        .HasForeignKey("backend.Features.AdaptivePlanning.WeeklyReportNutritionSummary", "WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportRecoverySummary", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithOne("RecoverySummary")
                        .HasForeignKey("backend.Features.AdaptivePlanning.WeeklyReportRecoverySummary", "WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportTrainingSummary", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithOne("TrainingSummary")
                        .HasForeignKey("backend.Features.AdaptivePlanning.WeeklyReportTrainingSummary", "WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReportWeightSummary", b =>
                {
                    b.HasOne("backend.Features.AdaptivePlanning.WeeklyReport", "WeeklyReport")
                        .WithOne("WeightSummary")
                        .HasForeignKey("backend.Features.AdaptivePlanning.WeeklyReportWeightSummary", "WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("backend.Features.Auth.RefreshToken", b =>
                {
                    b.HasOne("backend.Features.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Features.Food.ComposedMealIngredient", b =>
                {
                    b.HasOne("backend.Features.Food.ComposedMeal", "ComposedMeal")
                        .WithMany("Ingredients")
                        .HasForeignKey("ComposedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComposedMeal");
                });

            modelBuilder.Entity("backend.Features.Training.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("backend.Features.Training.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.SetLog", b =>
                {
                    b.HasOne("backend.Features.Training.WorkoutSessions.Entities.WorkoutExerciseLog", "WorkoutExerciseLog")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExerciseLog");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutExerciseLog", b =>
                {
                    b.HasOne("backend.Features.Training.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Features.Training.WorkoutSessions.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutSession", b =>
                {
                    b.HasOne("backend.Features.Training.Workouts.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Features.Training.WorkoutPrograms.WorkoutProgram", "WorkoutProgram")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Workout");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("backend.Features.Training.Workouts.Workout", b =>
                {
                    b.HasOne("backend.Features.Training.WorkoutPrograms.WorkoutProgram", "WorkoutProgram")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("backend.Features.Training.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("backend.Features.Training.Exercises.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Features.Training.Workouts.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("backend.Features.Users.UserSettings", b =>
                {
                    b.HasOne("backend.Features.Users.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("backend.Features.Users.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Features.Weight.WeightLog", b =>
                {
                    b.HasOne("backend.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.AdaptiveRecommendation", b =>
                {
                    b.Navigation("ExerciseTargetChange");

                    b.Navigation("NutritionChange");

                    b.Navigation("RecoveryAction");

                    b.Navigation("TargetDateChange");
                });

            modelBuilder.Entity("backend.Features.AdaptivePlanning.WeeklyReport", b =>
                {
                    b.Navigation("MuscleBalance");

                    b.Navigation("NextWeekActions");

                    b.Navigation("NutritionSummary");

                    b.Navigation("Recommendations");

                    b.Navigation("RecoverySummary");

                    b.Navigation("TrainingSummary");

                    b.Navigation("WeightSummary");
                });

            modelBuilder.Entity("backend.Features.Food.ComposedMeal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("backend.Features.Training.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscles");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutPrograms.WorkoutProgram", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutExerciseLog", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("backend.Features.Training.WorkoutSessions.Entities.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("backend.Features.Training.Workouts.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("backend.Features.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
