using backend.Data;
using backend.Features.AdaptivePlanning;
using backend.Features.Food;
using backend.Features.Training.Exercises;
using backend.Features.Training.WorkoutPrograms;
using backend.Features.Training.Workouts;
using backend.Features.Training.WorkoutSessions.Entities;
using backend.Features.Users;
using backend.Features.Weight;
using Microsoft.EntityFrameworkCore;

namespace backend.Features.Development
{
    public class DevelopmentSeedService
    {
        private const string SeedSourceType = "developmentMockData";
        private const string SeedSessionPrefix = "dev-seed-";
        private const string SeedNote = "Generated by local development mock data seeder.";
        private const string SeedProgramName = "Mock EvoliX Push Pull Legs";

        private readonly AppDbContext _db;
        private readonly WeeklyReportService _weeklyReportService;

        public DevelopmentSeedService(
            AppDbContext db,
            WeeklyReportService weeklyReportService)
        {
            _db = db;
            _weeklyReportService = weeklyReportService;
        }

        public async Task<DevelopmentSeedResult> SeedMockDataAsync(
            string userId,
            CancellationToken ct = default)
        {
            if (string.IsNullOrWhiteSpace(userId))
                throw new ArgumentException("UserId is required.", nameof(userId));

            var today = DateTime.UtcNow.Date;
            var foodAndWeightFrom = today.AddDays(-29);
            var trainingFrom = today.AddDays(-34);

            await RemoveExistingSeedDataAsync(userId, ct);
            var settings = await UpsertUserSettingsAsync(userId, today, ct);
            await UpsertCoachSettingsAsync(userId, ct);
            var exercises = await EnsureSeedExercisesAsync(userId, ct);
            var plan = await EnsureSeedWorkoutProgramAsync(userId, exercises, ct);
            var exerciseTargets = await ReplaceExerciseTargetsAsync(userId, exercises, ct);
            var nutritionTargetsHistory = await ReplaceNutritionTargetsHistoryAsync(
                userId,
                settings,
                today,
                ct);
            var composedMeals = await ReplaceComposedMealsAsync(userId, today, ct);

            var foodLogs = BuildFoodLogs(userId, foodAndWeightFrom, today);
            _db.FoodLogs.AddRange(foodLogs);

            var weightLogsChanged = await UpsertWeightLogsAsync(
                userId,
                foodAndWeightFrom,
                today,
                ct);

            var sessions = BuildWorkoutSessions(
                userId,
                trainingFrom,
                exercises,
                plan);
            _db.WorkoutSessions.AddRange(sessions);

            await _db.SaveChangesAsync(ct);

            var report = await _weeklyReportService.RegenerateCurrentAsync(userId, ct);
            var developmentRecommendations = BuildDevelopmentRecommendations(
                userId,
                today,
                report,
                settings,
                exercises);
            _db.AdaptiveRecommendations.AddRange(developmentRecommendations);

            await _db.SaveChangesAsync(ct);

            return new DevelopmentSeedResult
            {
                UserId = userId,
                FoodLogs = foodLogs.Count,
                WeightLogs = weightLogsChanged,
                WorkoutSessions = sessions.Count,
                Exercises = exercises.Count,
                WorkoutPrograms = 1,
                Workouts = plan.Workouts.Count,
                ComposedMeals = composedMeals,
                ExerciseTargets = exerciseTargets,
                NutritionTargetsHistory = nutritionTargetsHistory,
                AdaptiveRecommendations =
                    report.Recommendations.Count + developmentRecommendations.Count,
                FoodAndWeightFromUtc = foodAndWeightFrom,
                FoodAndWeightToUtc = today,
                TrainingFromUtc = trainingFrom,
                TrainingToUtc = sessions.Max(x => x.StartedAtUtc).Date
            };
        }

        private async Task RemoveExistingSeedDataAsync(
            string userId,
            CancellationToken ct)
        {
            var seedNutritionTargets = await _db.NutritionTargetsHistory
                .Where(x => x.UserId == userId && x.Source == SeedSourceType)
                .ToListAsync(ct);

            if (seedNutritionTargets.Count > 0)
            {
                _db.NutritionTargetsHistory.RemoveRange(seedNutritionTargets);
            }

            var seedReports = await _db.WeeklyReports
                .Where(x =>
                    x.UserId == userId &&
                    x.AlgorithmVersion == WeeklyReportService.AlgorithmVersion)
                .ToListAsync(ct);

            if (seedReports.Count > 0)
            {
                _db.WeeklyReports.RemoveRange(seedReports);
            }

            var seedFoodLogs = await _db.FoodLogs
                .Where(x => x.UserId == userId && x.SourceType == SeedSourceType)
                .ToListAsync(ct);

            if (seedFoodLogs.Count > 0)
            {
                _db.FoodLogs.RemoveRange(seedFoodLogs);
            }

            var seedSessions = await _db.WorkoutSessions
                .Where(x =>
                    x.UserId == userId &&
                    x.ClientRequestId != null &&
                    x.ClientRequestId.StartsWith(SeedSessionPrefix))
                .ToListAsync(ct);

            if (seedSessions.Count > 0)
            {
                _db.WorkoutSessions.RemoveRange(seedSessions);
            }

            var seedComposedMeals = await _db.ComposedMeals
                .Where(x => x.UserId == userId && x.Name.StartsWith("Mock "))
                .ToListAsync(ct);

            if (seedComposedMeals.Count > 0)
            {
                _db.ComposedMeals.RemoveRange(seedComposedMeals);
            }

            var seedWorkouts = await _db.Workouts
                .Where(x => x.UserId == userId && x.Name.StartsWith("Mock "))
                .ToListAsync(ct);

            if (seedWorkouts.Count > 0)
            {
                _db.Workouts.RemoveRange(seedWorkouts);
            }

            var seedPrograms = await _db.WorkoutPrograms
                .Where(x => x.UserId == userId && x.Name == SeedProgramName)
                .ToListAsync(ct);

            if (seedPrograms.Count > 0)
            {
                _db.WorkoutPrograms.RemoveRange(seedPrograms);
            }

            if (seedNutritionTargets.Count > 0 ||
                seedReports.Count > 0 ||
                seedFoodLogs.Count > 0 ||
                seedSessions.Count > 0 ||
                seedComposedMeals.Count > 0 ||
                seedWorkouts.Count > 0 ||
                seedPrograms.Count > 0)
            {
                await _db.SaveChangesAsync(ct);
            }
        }

        private async Task<UserSettings> UpsertUserSettingsAsync(
            string userId,
            DateTime today,
            CancellationToken ct)
        {
            var settings = await _db.UserSettings
                .FirstOrDefaultAsync(x => x.UserId == userId, ct);

            if (settings == null)
            {
                settings = new UserSettings
                {
                    Id = Guid.NewGuid(),
                    UserId = userId
                };
                _db.UserSettings.Add(settings);
            }

            settings.CalorieGoal = 2450;
            settings.ProteinGoal = 185;
            settings.FatGoal = 75;
            settings.CarbGoal = 255;
            settings.WeightGoalKg = 82m;
            settings.WeightGoalTimeUtc = today.AddDays(70).AddHours(12);
            settings.WeightDirection = WeightDirection.Lose;
            settings.MuscleFilter = MuscleFilter.Advanced;
            settings.HomeProgressCirclesJson = "[\"calories\",\"protein\",\"carbs\",\"fat\"]";
            settings.HomeSectionOrderJson = "[\"quickStart\",\"goals\",\"weight\",\"recoveryMap\"]";
            settings.RecoveryMapHiddenMusclesJson = "[]";
            settings.FoodCoachExcludedDateKeysJson = "[]";
            settings.ShowOnlyCustomTrainingContent = false;
            settings.UseFoodCoach = true;
            settings.UseWorkoutCoach = true;
            settings.UpdatedUtc = DateTime.UtcNow;
            settings.SchemaVersion = Math.Max(settings.SchemaVersion, 1);

            await _db.SaveChangesAsync(ct);
            return settings;
        }

        private async Task UpsertCoachSettingsAsync(
            string userId,
            CancellationToken ct)
        {
            var settings = await _db.CoachSettings
                .FirstOrDefaultAsync(x => x.UserId == userId, ct);

            if (settings == null)
            {
                settings = new CoachSettings
                {
                    UserId = userId
                };
                _db.CoachSettings.Add(settings);
            }

            settings.AdaptiveNutritionEnabled = true;
            settings.AdaptiveTrainingEnabled = true;
            settings.AutoApplyLowRiskSuggestions = false;
            settings.PreferredReportDay = 1;
            settings.AggressivenessLevel = AggressivenessLevel.Balanced;
            settings.UpdatedAtUtc = DateTime.UtcNow;

            await _db.SaveChangesAsync(ct);
        }

        private async Task<Dictionary<string, Exercise>> EnsureSeedExercisesAsync(
            string userId,
            CancellationToken ct)
        {
            var specs = ExerciseSpecs();
            var names = specs.Select(x => x.Name).ToList();
            var existing = await _db.Exercises
                .Where(x => x.UserId == userId && names.Contains(x.Name))
                .ToListAsync(ct);
            var byName = existing
                .GroupBy(x => x.Name, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(x => x.Key, x => x.First(), StringComparer.OrdinalIgnoreCase);
            var existingExerciseIds = existing.Select(x => x.Id).ToList();

            if (existingExerciseIds.Count > 0)
            {
                await _db.ExerciseMuscles
                    .Where(x => existingExerciseIds.Contains(x.ExerciseId))
                    .ExecuteDeleteAsync(ct);
            }

            foreach (var spec in specs)
            {
                if (!byName.TryGetValue(spec.Name, out var exercise))
                {
                    exercise = new Exercise
                    {
                        Name = spec.Name,
                        Description = SeedNote,
                        Muscle = spec.Muscle,
                        SpecificMuscleGroups = string.Join(", ", spec.Muscles.Select(x => x.Muscle)),
                        Equipment = spec.Equipment,
                        Category = "Strength",
                        EquipmentType = spec.Equipment,
                        IsBodyweight = spec.IsBodyweight,
                        IsIsolation = spec.IsIsolation,
                        IsCompound = !spec.IsIsolation,
                        DefaultProgressionStepKg = spec.ProgressionStepKg,
                        UserId = userId
                    };

                    exercise.ExerciseMuscles = BuildExerciseMuscles(exercise.Id, spec.Muscles);
                    _db.Exercises.Add(exercise);
                    byName[spec.Name] = exercise;
                    continue;
                }

                exercise.Description = SeedNote;
                exercise.Muscle = spec.Muscle;
                exercise.SpecificMuscleGroups = string.Join(", ", spec.Muscles.Select(x => x.Muscle));
                exercise.Equipment = spec.Equipment;
                exercise.Category = "Strength";
                exercise.EquipmentType = spec.Equipment;
                exercise.IsBodyweight = spec.IsBodyweight;
                exercise.IsIsolation = spec.IsIsolation;
                exercise.IsCompound = !spec.IsIsolation;
                exercise.DefaultProgressionStepKg = spec.ProgressionStepKg;

                var replacementMuscles = BuildExerciseMuscles(exercise.Id, spec.Muscles);
                _db.ExerciseMuscles.AddRange(replacementMuscles);
                exercise.ExerciseMuscles = replacementMuscles;
            }

            await _db.SaveChangesAsync(ct);
            return byName;
        }

        private static List<ExerciseMuscle> BuildExerciseMuscles(
            Guid exerciseId,
            IReadOnlyList<MuscleSpec> muscles)
        {
            return muscles
                .Select(x => new ExerciseMuscle
                {
                    ExerciseId = exerciseId,
                    Muscle = x.Muscle,
                    Role = x.Role,
                    Contribution = x.Contribution
                })
                .ToList();
        }

        private async Task<SeedWorkoutProgram> EnsureSeedWorkoutProgramAsync(
            string userId,
            IReadOnlyDictionary<string, Exercise> exercises,
            CancellationToken ct)
        {
            var program = await _db.WorkoutPrograms
                .FirstOrDefaultAsync(
                    x => x.UserId == userId && x.Name == SeedProgramName,
                    ct);

            if (program == null)
            {
                program = new WorkoutProgram
                {
                    Id = Guid.NewGuid(),
                    Name = SeedProgramName,
                    Goal = "Muskelvekst og styrke med EvoliX-planlegging",
                    Level = "Viderekommen",
                    UserId = userId
                };
                _db.WorkoutPrograms.Add(program);
            }
            else
            {
                program.Goal = "Muskelvekst og styrke med EvoliX-planlegging";
                program.Level = "Viderekommen";
            }

            var specs = SeedWorkoutSpecs();
            var workoutNames = specs.Select(x => x.Name).ToList();
            var existingWorkouts = await _db.Workouts
                .Include(x => x.WorkoutExercises)
                .Where(x => x.UserId == userId && workoutNames.Contains(x.Name))
                .ToListAsync(ct);
            var byName = existingWorkouts.ToDictionary(x => x.Name, StringComparer.OrdinalIgnoreCase);
            var bySplit = new Dictionary<SplitType, Workout>();

            foreach (var spec in specs)
            {
                if (!byName.TryGetValue(spec.Name, out var workout))
                {
                    workout = new Workout
                    {
                        Id = Guid.NewGuid(),
                        Name = spec.Name,
                        UserId = userId
                    };
                    _db.Workouts.Add(workout);
                }
                else if (workout.WorkoutExercises.Count > 0)
                {
                    _db.WorkoutExercises.RemoveRange(workout.WorkoutExercises);
                    workout.WorkoutExercises.Clear();
                }

                workout.Description = spec.Description;
                workout.DayLabel = spec.DayLabel;
                workout.WorkoutProgramId = program.Id;

                var exerciseIds = WorkoutPlans(spec.Split)
                    .Select(x => exercises[x.ExerciseName].Id)
                    .ToList();

                foreach (var workoutExercise in exerciseIds.Select((exerciseId, index) => new WorkoutExercise
                {
                    WorkoutId = workout.Id,
                    ExerciseId = exerciseId,
                    Order = index + 1
                }))
                {
                    workout.WorkoutExercises.Add(workoutExercise);
                }

                bySplit[spec.Split] = workout;
            }

            await _db.SaveChangesAsync(ct);
            return new SeedWorkoutProgram(program, bySplit);
        }

        private async Task<int> ReplaceExerciseTargetsAsync(
            string userId,
            IReadOnlyDictionary<string, Exercise> exercises,
            CancellationToken ct)
        {
            var seedExerciseIds = exercises.Values.Select(x => x.Id).ToList();
            var existing = await _db.ExerciseTargets
                .Where(x => x.UserId == userId && seedExerciseIds.Contains(x.ExerciseId))
                .ToListAsync(ct);

            if (existing.Count > 0)
            {
                _db.ExerciseTargets.RemoveRange(existing);
                await _db.SaveChangesAsync(ct);
            }

            var targets = ExerciseTargetSpecs()
                .Select(spec => new ExerciseTarget
                {
                    UserId = userId,
                    ExerciseId = exercises[spec.ExerciseName].Id,
                    TargetSets = spec.TargetSets,
                    MinReps = spec.MinReps,
                    MaxReps = spec.MaxReps,
                    TargetWeightKg = spec.TargetWeightKg,
                    ProgressionModel = spec.ProgressionModel,
                    UpdatedAtUtc = DateTime.UtcNow
                })
                .ToList();

            _db.ExerciseTargets.AddRange(targets);
            await _db.SaveChangesAsync(ct);
            return targets.Count;
        }

        private async Task<int> ReplaceNutritionTargetsHistoryAsync(
            string userId,
            UserSettings settings,
            DateTime today,
            CancellationToken ct)
        {
            var entries = new List<NutritionTargetsHistory>
            {
                new()
                {
                    UserId = userId,
                    Calories = 2550,
                    Protein = 175,
                    Carbs = 280,
                    Fat = 75,
                    Source = SeedSourceType,
                    CreatedAtUtc = today.AddDays(-28).AddHours(7),
                    ActiveFrom = today.AddDays(-28)
                },
                new()
                {
                    UserId = userId,
                    Calories = 2500,
                    Protein = 180,
                    Carbs = 265,
                    Fat = 75,
                    Source = SeedSourceType,
                    CreatedAtUtc = today.AddDays(-14).AddHours(7),
                    ActiveFrom = today.AddDays(-14)
                },
                new()
                {
                    UserId = userId,
                    Calories = settings.CalorieGoal,
                    Protein = settings.ProteinGoal,
                    Carbs = settings.CarbGoal,
                    Fat = settings.FatGoal,
                    Source = SeedSourceType,
                    CreatedAtUtc = today.AddDays(-1).AddHours(7),
                    ActiveFrom = today.AddDays(-1)
                }
            };

            _db.NutritionTargetsHistory.AddRange(entries);
            await _db.SaveChangesAsync(ct);
            return entries.Count;
        }

        private async Task<int> ReplaceComposedMealsAsync(
            string userId,
            DateTime today,
            CancellationToken ct)
        {
            var meals = new List<ComposedMeal>
            {
                new()
                {
                    UserId = userId,
                    Name = "Mock Frokostbolle",
                    IsFavorite = true,
                    CreatedUtc = today.AddDays(-20).AddHours(8),
                    UpdatedUtc = today.AddDays(-3).AddHours(8),
                    LastUsedUtc = today.AddDays(-1).AddHours(8),
                    Ingredients =
                    {
                        new ComposedMealIngredient { Name = "Havregryn", AmountGrams = 80, Calories = 296, Proteins = 10, Carbs = 48, Fats = 6, SortOrder = 1 },
                        new ComposedMealIngredient { Name = "Skyr naturell", AmountGrams = 250, Calories = 165, Proteins = 28, Carbs = 10, Fats = 1, SortOrder = 2 },
                        new ComposedMealIngredient { Name = "Blåbær", AmountGrams = 80, Calories = 45, Proteins = 1, Carbs = 10, Fats = 0, SortOrder = 3 }
                    }
                },
                new()
                {
                    UserId = userId,
                    Name = "Mock Kylling og ris",
                    IsFavorite = true,
                    CreatedUtc = today.AddDays(-18).AddHours(12),
                    UpdatedUtc = today.AddDays(-2).AddHours(12),
                    LastUsedUtc = today.AddDays(-2).AddHours(12),
                    Ingredients =
                    {
                        new ComposedMealIngredient { Name = "Kyllingfilet", AmountGrams = 180, Calories = 198, Proteins = 42, Carbs = 0, Fats = 3, SortOrder = 1 },
                        new ComposedMealIngredient { Name = "Jasminris", AmountGrams = 260, Calories = 338, Proteins = 7, Carbs = 75, Fats = 1, SortOrder = 2 },
                        new ComposedMealIngredient { Name = "Avokado", AmountGrams = 70, Calories = 112, Proteins = 1, Carbs = 6, Fats = 10, SortOrder = 3 }
                    }
                },
                new()
                {
                    UserId = userId,
                    Name = "Mock Laksebolle",
                    IsFavorite = false,
                    CreatedUtc = today.AddDays(-12).AddHours(18),
                    UpdatedUtc = today.AddDays(-1).AddHours(18),
                    LastUsedUtc = today.AddDays(-4).AddHours(18),
                    Ingredients =
                    {
                        new ComposedMealIngredient { Name = "Laks", AmountGrams = 180, Calories = 374, Proteins = 36, Carbs = 0, Fats = 24, SortOrder = 1 },
                        new ComposedMealIngredient { Name = "Poteter", AmountGrams = 300, Calories = 231, Proteins = 6, Carbs = 51, Fats = 0, SortOrder = 2 },
                        new ComposedMealIngredient { Name = "Grønne bønner", AmountGrams = 120, Calories = 37, Proteins = 2, Carbs = 8, Fats = 0, SortOrder = 3 }
                    }
                }
            };

            _db.ComposedMeals.AddRange(meals);
            await _db.SaveChangesAsync(ct);
            return meals.Count;
        }

        private static List<FoodLog> BuildFoodLogs(
            string userId,
            DateTime fromDay,
            DateTime toDay)
        {
            var meals = new[]
            {
                new MealTemplate("Oatmeal bowl", 520, 36, 70, 14, 7),
                new MealTemplate("Chicken rice bowl", 690, 52, 82, 17, 12),
                new MealTemplate("Skyr, banana and almonds", 360, 32, 42, 8, 15),
                new MealTemplate("Salmon, potatoes and greens", 760, 48, 74, 28, 18)
            };

            var logs = new List<FoodLog>();
            var dayCount = (int)(toDay - fromDay).TotalDays + 1;

            for (var dayIndex = 0; dayIndex < dayCount; dayIndex++)
            {
                var day = fromDay.AddDays(dayIndex);
                var isTrainingDay = day.DayOfWeek != DayOfWeek.Sunday;
                var dailyAdjustment = isTrainingDay ? 1.04 : 0.94;
                var wave = Math.Sin(dayIndex * 0.75) * 0.04;

                for (var mealIndex = 0; mealIndex < meals.Length; mealIndex++)
                {
                    var meal = meals[mealIndex];
                    var factor = dailyAdjustment + wave + (mealIndex == 3 ? 0.03 : 0);
                    logs.Add(new FoodLog
                    {
                        UserId = userId,
                        Title = meal.Title,
                        Calories = ScaleInt(meal.Calories, factor),
                        Proteins = ScaleInt(meal.Proteins, factor),
                        Carbs = ScaleInt(meal.Carbs, factor),
                        Fats = ScaleInt(meal.Fats, factor),
                        TimestampUtc = day.AddHours(meal.HourUtc).AddMinutes((dayIndex % 4) * 7),
                        SourceType = SeedSourceType,
                        SourceServings = 1m
                    });
                }
            }

            return logs;
        }

        private async Task<int> UpsertWeightLogsAsync(
            string userId,
            DateTime fromDay,
            DateTime toDay,
            CancellationToken ct)
        {
            var existing = await _db.WeightLogs
                .Where(x =>
                    x.UserId == userId &&
                    x.TimestampUtc >= fromDay &&
                    x.TimestampUtc < toDay.AddDays(1))
                .ToListAsync(ct);

            var byDay = existing
                .GroupBy(x => x.TimestampUtc.Date)
                .ToDictionary(x => x.Key, x => x.First());

            var dayCount = (int)(toDay - fromDay).TotalDays + 1;

            for (var dayIndex = 0; dayIndex < dayCount; dayIndex++)
            {
                var day = fromDay.AddDays(dayIndex);
                var trend = 86.4 - (dayIndex * 0.035);
                var noise = Math.Sin(dayIndex * 1.7) * 0.18 + Math.Cos(dayIndex * 0.41) * 0.07;
                var weightKg = Math.Round(trend + noise, 1, MidpointRounding.AwayFromZero);
                var timestamp = day.AddHours(6).AddMinutes(20 + dayIndex % 11);

                if (byDay.TryGetValue(day, out var existingLog))
                {
                    existingLog.WeightKg = weightKg;
                    existingLog.TimestampUtc = timestamp;
                    continue;
                }

                _db.WeightLogs.Add(new WeightLog
                {
                    UserId = userId,
                    WeightKg = weightKg,
                    TimestampUtc = timestamp
                });
            }

            return dayCount;
        }

        private static List<WorkoutSession> BuildWorkoutSessions(
            string userId,
            DateTime trainingFrom,
            IReadOnlyDictionary<string, Exercise> exercises,
            SeedWorkoutProgram plan)
        {
            var sessions = new List<WorkoutSession>();
            var counts = new Dictionary<SplitType, int>
            {
                [SplitType.Push] = 0,
                [SplitType.Pull] = 0,
                [SplitType.Legs] = 0
            };

            for (var dayOffset = 0; counts.Values.Any(x => x < 10); dayOffset++)
            {
                var cycleDay = dayOffset % 7;
                if (cycleDay == 6) continue;

                var split = cycleDay switch
                {
                    0 or 3 => SplitType.Push,
                    1 or 4 => SplitType.Pull,
                    _ => SplitType.Legs
                };

                if (counts[split] >= 10) continue;

                var occurrence = counts[split];
                counts[split]++;
                var startedAt = trainingFrom
                    .AddDays(dayOffset)
                    .AddHours(16)
                    .AddMinutes(25 + (occurrence % 4) * 8);

                sessions.Add(BuildWorkoutSession(
                    userId,
                    split,
                    occurrence,
                    startedAt,
                    exercises,
                    plan));
            }

            return sessions;
        }

        private static WorkoutSession BuildWorkoutSession(
            string userId,
            SplitType split,
            int occurrence,
            DateTime startedAt,
            IReadOnlyDictionary<string, Exercise> exercises,
            SeedWorkoutProgram plan)
        {
            var plans = WorkoutPlans(split);
            var workout = plan.Workouts[split];
            var session = new WorkoutSession
            {
                UserId = userId,
                ClientRequestId = $"{SeedSessionPrefix}{split.ToString().ToLowerInvariant()}-{occurrence + 1:D2}",
                WorkoutId = workout.Id,
                WorkoutProgramId = plan.Program.Id,
                StartedAtUtc = startedAt,
                FinishedAtUtc = startedAt.AddMinutes(62 + (occurrence % 5) * 4),
                Title = $"{workout.DayLabel} #{occurrence + 1}",
                Notes = SeedNote
            };

            for (var exerciseIndex = 0; exerciseIndex < plans.Count; exerciseIndex++)
            {
                var exercisePlan = plans[exerciseIndex];
                var exerciseLog = new WorkoutExerciseLog
                {
                    ExerciseId = exercises[exercisePlan.ExerciseName].Id,
                    Order = exerciseIndex + 1
                };

                for (var setIndex = 0; setIndex < exercisePlan.Sets; setIndex++)
                {
                    var weight = RoundToNearest(
                        exercisePlan.StartWeightKg + occurrence * exercisePlan.ProgressionKg - setIndex * exercisePlan.BackoffKg,
                        2.5);
                    var reps = Math.Max(5, exercisePlan.TargetReps - ((occurrence + setIndex) % 2));

                    exerciseLog.Sets.Add(new SetLog
                    {
                        SetNumber = setIndex + 1,
                        WeightKg = weight,
                        Reps = reps,
                        Rir = Math.Round(1.5 + ((occurrence + setIndex) % 4) * 0.5, 1),
                        SetType = setIndex == 0 ? "top" : "backoff"
                    });
                }

                session.ExerciseLogs.Add(exerciseLog);
            }

            RecalculateTotals(session);
            return session;
        }

        private static void RecalculateTotals(WorkoutSession session)
        {
            var sets = session.ExerciseLogs.SelectMany(x => x.Sets).ToList();
            session.TotalSets = sets.Count;
            session.TotalReps = sets.Where(x => x.Reps.HasValue).Sum(x => x.Reps!.Value);
            session.TotalVolume = sets
                .Where(x => x.WeightKg.HasValue && x.Reps.HasValue)
                .Sum(x => x.WeightKg!.Value * x.Reps!.Value);
        }

        private static List<AdaptiveRecommendation> BuildDevelopmentRecommendations(
            string userId,
            DateTime today,
            WeeklyReport report,
            UserSettings settings,
            IReadOnlyDictionary<string, Exercise> exercises)
        {
            var createdAt = DateTime.UtcNow;
            var appliesFrom = DateOnly.FromDateTime(today).AddDays(1);
            var expiresAt = createdAt.AddDays(7);

            var recommendations = new List<AdaptiveRecommendation>
            {
                new()
                {
                    UserId = userId,
                    SourceReportId = report.Id,
                    Type = AdaptiveRecommendationType.IncreaseLoad,
                    Title = "Øk benkpress kontrollert",
                    Explanation = "De siste øktene viser stigende estimert 1RM og stabil RIR. EvoliX foreslår en liten vektøkning i neste benkpressøkt.",
                    Confidence = RecommendationConfidence.High,
                    CreatedAtUtc = createdAt.AddMinutes(-18),
                    AppliesFromDate = appliesFrom,
                    ExpiresAtUtc = expiresAt,
                    ExerciseTargetChange = new RecommendationExerciseTargetChange
                    {
                        ExerciseId = exercises["Mock Bench Press"].Id,
                        CurrentTargetSets = 4,
                        SuggestedTargetSets = 4,
                        MinReps = 6,
                        MaxReps = 8,
                        CurrentTargetWeightKg = 97.5m,
                        SuggestedTargetWeightKg = 100m,
                        ProgressionModel = ExerciseProgressionModel.DoubleProgression
                    }
                },
                new()
                {
                    UserId = userId,
                    SourceReportId = report.Id,
                    Type = AdaptiveRecommendationType.AddSet,
                    Title = "Legg til ett arbeidssett på pull-up",
                    Explanation = "Ryggvolumet tåler litt mer akkurat nå. EvoliX foreslår ett ekstra kontrollert sett før belastningen økes videre.",
                    Confidence = RecommendationConfidence.Medium,
                    CreatedAtUtc = createdAt.AddMinutes(-16),
                    AppliesFromDate = appliesFrom,
                    ExpiresAtUtc = expiresAt,
                    ExerciseTargetChange = new RecommendationExerciseTargetChange
                    {
                        ExerciseId = exercises["Mock Pull-up"].Id,
                        CurrentTargetSets = 4,
                        SuggestedTargetSets = 5,
                        MinReps = 6,
                        MaxReps = 9,
                        CurrentTargetWeightKg = 10m,
                        SuggestedTargetWeightKg = 10m,
                        ProgressionModel = ExerciseProgressionModel.DoubleProgression
                    }
                },
                new()
                {
                    UserId = userId,
                    SourceReportId = report.Id,
                    Type = AdaptiveRecommendationType.RecoveryNextSession,
                    Title = "Neste økt bør være pull",
                    Explanation = "Bryst, triceps og fremside lår er nylig belastet. Rygg og biceps ser mest klare ut for neste kvalitetsøkt.",
                    Confidence = RecommendationConfidence.High,
                    CreatedAtUtc = createdAt.AddMinutes(-14),
                    AppliesFromDate = appliesFrom,
                    ExpiresAtUtc = expiresAt,
                    RecoveryAction = new RecommendationRecoveryAction
                    {
                        RecommendedSession = "Pull",
                        Intensity = "Moderat/tung",
                        FocusMusclesText = "Lats, øvre rygg, biceps",
                        RestMusclesText = "Bryst, triceps, quadriceps"
                    }
                },
                new()
                {
                    UserId = userId,
                    SourceReportId = report.Id,
                    Type = AdaptiveRecommendationType.AdjustTargetDate,
                    Title = "Flytt måldatoen litt ut",
                    Explanation = "Tempoet er bra, men måldatoen er stram. En roligere frist gjør planen mer realistisk uten å kutte kaloriene hardt.",
                    Confidence = RecommendationConfidence.Medium,
                    CreatedAtUtc = createdAt.AddMinutes(-12),
                    AppliesFromDate = appliesFrom,
                    ExpiresAtUtc = expiresAt,
                    TargetDateChange = new RecommendationTargetDateChange
                    {
                        CurrentTargetDateUtc = settings.WeightGoalTimeUtc,
                        SuggestedTargetDateUtc = settings.WeightGoalTimeUtc.AddDays(14),
                        CurrentWeeklyPaceKg = -0.44,
                        SuggestedWeeklyPaceKg = -0.35
                    }
                },
                new()
                {
                    UserId = userId,
                    SourceReportId = report.Id,
                    Type = AdaptiveRecommendationType.PrioritizeMuscle,
                    Title = "Prioriter bakside skulder denne uken",
                    Explanation = "Pressvolumet er høyt sammenlignet med trekk for bakside skulder. Legg face pull tidlig i pulløkten for bedre balanse.",
                    Confidence = RecommendationConfidence.Medium,
                    CreatedAtUtc = createdAt.AddMinutes(-10),
                    AppliesFromDate = appliesFrom,
                    ExpiresAtUtc = expiresAt,
                    ExerciseTargetChange = new RecommendationExerciseTargetChange
                    {
                        ExerciseId = exercises["Mock Face Pull"].Id,
                        CurrentTargetSets = 3,
                        SuggestedTargetSets = 4,
                        MinReps = 12,
                        MaxReps = 16,
                        CurrentTargetWeightKg = 30m,
                        SuggestedTargetWeightKg = 30m,
                        ProgressionModel = ExerciseProgressionModel.Maintain
                    }
                }
            };

            return recommendations;
        }

        private static int ScaleInt(int value, double factor)
        {
            return Math.Max(0, (int)Math.Round(value * factor, MidpointRounding.AwayFromZero));
        }

        private static double RoundToNearest(double value, double step)
        {
            return Math.Round(value / step, MidpointRounding.AwayFromZero) * step;
        }

        private static IReadOnlyList<ExerciseSpec> ExerciseSpecs()
        {
            return
            [
                new ExerciseSpec(
                    "Mock Bench Press",
                    "Bryst",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Bryst", MuscleRole.Primary, 1m), new("Triceps", MuscleRole.Secondary, 0.45m), new("Fremre skulder", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Incline DB Press",
                    "Bryst",
                    "Dumbbell",
                    false,
                    false,
                    2.5m,
                    [new("Bryst", MuscleRole.Primary, 1m), new("Fremre skulder", MuscleRole.Secondary, 0.55m), new("Triceps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Overhead Press",
                    "Skuldre",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Fremre skulder", MuscleRole.Primary, 1m), new("Sideskulder", MuscleRole.Secondary, 0.45m), new("Triceps", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Lateral Raise",
                    "Skuldre",
                    "Dumbbell",
                    false,
                    true,
                    1m,
                    [new("Sideskulder", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Triceps Pushdown",
                    "Armer",
                    "Cable",
                    false,
                    true,
                    2.5m,
                    [new("Triceps", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Deadlift",
                    "Rygg",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.65m), new("Nedre rygg", MuscleRole.Secondary, 0.55m), new("Traps", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Pull-up",
                    "Rygg",
                    "Bodyweight",
                    true,
                    false,
                    1.25m,
                    [new("Lats", MuscleRole.Primary, 1m), new("Biceps", MuscleRole.Secondary, 0.55m), new("Traps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Barbell Row",
                    "Rygg",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Lats", MuscleRole.Primary, 1m), new("Traps", MuscleRole.Secondary, 0.5m), new("Biceps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Face Pull",
                    "Skuldre",
                    "Cable",
                    false,
                    true,
                    2.5m,
                    [new("Bakre skulder", MuscleRole.Primary, 1m), new("Traps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Hammer Curl",
                    "Armer",
                    "Dumbbell",
                    false,
                    true,
                    1m,
                    [new("Biceps", MuscleRole.Primary, 1m), new("Brachialis", MuscleRole.Secondary, 0.6m)]),
                new ExerciseSpec(
                    "Mock Squat",
                    "Bein",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Quadriceps", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.65m), new("Hamstrings", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Romanian Deadlift",
                    "Bein",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.7m), new("Nedre rygg", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Leg Press",
                    "Bein",
                    "Machine",
                    false,
                    false,
                    5m,
                    [new("Quadriceps", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Leg Curl",
                    "Bein",
                    "Machine",
                    false,
                    true,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Standing Calf Raise",
                    "Bein",
                    "Machine",
                    false,
                    true,
                    5m,
                    [new("Bakside legg", MuscleRole.Primary, 1m)])
            ];
        }

        private static IReadOnlyList<SeedWorkoutSpec> SeedWorkoutSpecs()
        {
            return
            [
                new(
                    SplitType.Push,
                    "Mock Push Strength",
                    "Push",
                    "Bryst, skuldre og triceps med progresjon fra EvoliX."),
                new(
                    SplitType.Pull,
                    "Mock Pull Strength",
                    "Pull",
                    "Rygg, bakside skulder og biceps med recovery-styrt progresjon."),
                new(
                    SplitType.Legs,
                    "Mock Legs Strength",
                    "Bein",
                    "Knebøy, hoftehengsel og beinvolum tilpasset ukesplanen.")
            ];
        }

        private static IReadOnlyList<ExerciseTargetSpec> ExerciseTargetSpecs()
        {
            return
            [
                new("Mock Bench Press", 4, 6, 8, 97.5m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Incline DB Press", 3, 8, 10, 36m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Overhead Press", 3, 6, 8, 57.5m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Lateral Raise", 3, 12, 16, 14m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Triceps Pushdown", 3, 10, 14, 37.5m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Deadlift", 3, 4, 6, 147.5m, ExerciseProgressionModel.Linear),
                new("Mock Pull-up", 4, 6, 9, 10m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Barbell Row", 3, 8, 10, 90m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Face Pull", 3, 12, 16, 30m, ExerciseProgressionModel.Maintain),
                new("Mock Hammer Curl", 3, 10, 12, 20m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Squat", 4, 5, 8, 122.5m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Romanian Deadlift", 3, 6, 9, 110m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Leg Press", 3, 10, 14, 205m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Leg Curl", 3, 10, 14, 55m, ExerciseProgressionModel.DoubleProgression),
                new("Mock Standing Calf Raise", 4, 10, 15, 105m, ExerciseProgressionModel.DoubleProgression)
            ];
        }

        private static IReadOnlyList<WorkoutExercisePlan> WorkoutPlans(SplitType split)
        {
            return split switch
            {
                SplitType.Push =>
                [
                    new("Mock Bench Press", 4, 8, 82.5, 1.5, 2.5),
                    new("Mock Incline DB Press", 3, 10, 32.5, 0.75, 1.25),
                    new("Mock Overhead Press", 3, 8, 50, 1.0, 2.5),
                    new("Mock Lateral Raise", 3, 14, 12.5, 0.25, 0.5),
                    new("Mock Triceps Pushdown", 3, 12, 32.5, 0.75, 1.25)
                ],
                SplitType.Pull =>
                [
                    new("Mock Deadlift", 3, 5, 130, 2.0, 5),
                    new("Mock Pull-up", 4, 8, 5, 0.75, 1.25),
                    new("Mock Barbell Row", 3, 9, 75, 1.5, 2.5),
                    new("Mock Face Pull", 3, 14, 27.5, 0.5, 1.25),
                    new("Mock Hammer Curl", 3, 11, 17.5, 0.5, 1.0)
                ],
                _ =>
                [
                    new("Mock Squat", 4, 7, 105, 1.75, 2.5),
                    new("Mock Romanian Deadlift", 3, 8, 95, 1.5, 2.5),
                    new("Mock Leg Press", 3, 12, 170, 3.0, 5),
                    new("Mock Leg Curl", 3, 12, 47.5, 1.0, 2.5),
                    new("Mock Standing Calf Raise", 4, 13, 85, 2.0, 5)
                ]
            };
        }

        private enum SplitType
        {
            Push,
            Pull,
            Legs
        }

        private sealed record MealTemplate(
            string Title,
            int Calories,
            int Proteins,
            int Carbs,
            int Fats,
            int HourUtc);

        private sealed record MuscleSpec(
            string Muscle,
            MuscleRole Role,
            decimal Contribution);

        private sealed record ExerciseSpec(
            string Name,
            string Muscle,
            string Equipment,
            bool IsBodyweight,
            bool IsIsolation,
            decimal ProgressionStepKg,
            IReadOnlyList<MuscleSpec> Muscles);

        private sealed record SeedWorkoutProgram(
            WorkoutProgram Program,
            IReadOnlyDictionary<SplitType, Workout> Workouts);

        private sealed record SeedWorkoutSpec(
            SplitType Split,
            string Name,
            string DayLabel,
            string Description);

        private sealed record ExerciseTargetSpec(
            string ExerciseName,
            int TargetSets,
            int MinReps,
            int MaxReps,
            decimal? TargetWeightKg,
            ExerciseProgressionModel ProgressionModel);

        private sealed record WorkoutExercisePlan(
            string ExerciseName,
            int Sets,
            int TargetReps,
            double StartWeightKg,
            double ProgressionKg,
            double BackoffKg);
    }
}
