using backend.Data;
using backend.Features.Food;
using backend.Features.Training.Exercises;
using backend.Features.Training.WorkoutSessions.Entities;
using backend.Features.Weight;
using Microsoft.EntityFrameworkCore;

namespace backend.Features.Development
{
    public class DevelopmentSeedService
    {
        private const string SeedSourceType = "developmentMockData";
        private const string SeedSessionPrefix = "dev-seed-";
        private const string SeedNote = "Generated by local development mock data seeder.";

        private readonly AppDbContext _db;

        public DevelopmentSeedService(AppDbContext db)
        {
            _db = db;
        }

        public async Task<DevelopmentSeedResult> SeedMockDataAsync(
            string userId,
            CancellationToken ct = default)
        {
            if (string.IsNullOrWhiteSpace(userId))
                throw new ArgumentException("UserId is required.", nameof(userId));

            var today = DateTime.UtcNow.Date;
            var foodAndWeightFrom = today.AddDays(-29);
            var trainingFrom = today.AddDays(-34);

            await RemoveExistingSeedDataAsync(userId, ct);
            var exercises = await EnsureSeedExercisesAsync(userId, ct);

            var foodLogs = BuildFoodLogs(userId, foodAndWeightFrom, today);
            _db.FoodLogs.AddRange(foodLogs);

            var weightLogsChanged = await UpsertWeightLogsAsync(
                userId,
                foodAndWeightFrom,
                today,
                ct);

            var sessions = BuildWorkoutSessions(
                userId,
                trainingFrom,
                exercises);
            _db.WorkoutSessions.AddRange(sessions);

            await _db.SaveChangesAsync(ct);

            return new DevelopmentSeedResult
            {
                FoodLogs = foodLogs.Count,
                WeightLogs = weightLogsChanged,
                WorkoutSessions = sessions.Count,
                Exercises = exercises.Count,
                FoodAndWeightFromUtc = foodAndWeightFrom,
                FoodAndWeightToUtc = today,
                TrainingFromUtc = trainingFrom,
                TrainingToUtc = sessions.Max(x => x.StartedAtUtc).Date
            };
        }

        private async Task RemoveExistingSeedDataAsync(
            string userId,
            CancellationToken ct)
        {
            var seedFoodLogs = await _db.FoodLogs
                .Where(x => x.UserId == userId && x.SourceType == SeedSourceType)
                .ToListAsync(ct);

            if (seedFoodLogs.Count > 0)
            {
                _db.FoodLogs.RemoveRange(seedFoodLogs);
            }

            var seedSessions = await _db.WorkoutSessions
                .Where(x =>
                    x.UserId == userId &&
                    x.ClientRequestId != null &&
                    x.ClientRequestId.StartsWith(SeedSessionPrefix))
                .ToListAsync(ct);

            if (seedSessions.Count > 0)
            {
                _db.WorkoutSessions.RemoveRange(seedSessions);
            }

            if (seedFoodLogs.Count > 0 || seedSessions.Count > 0)
            {
                await _db.SaveChangesAsync(ct);
            }
        }

        private async Task<Dictionary<string, Exercise>> EnsureSeedExercisesAsync(
            string userId,
            CancellationToken ct)
        {
            var specs = ExerciseSpecs();
            var names = specs.Select(x => x.Name).ToList();
            var existing = await _db.Exercises
                .Include(x => x.ExerciseMuscles)
                .Where(x => x.UserId == userId && names.Contains(x.Name))
                .ToListAsync(ct);
            var byName = existing
                .GroupBy(x => x.Name, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(x => x.Key, x => x.First(), StringComparer.OrdinalIgnoreCase);

            foreach (var spec in specs)
            {
                if (!byName.TryGetValue(spec.Name, out var exercise))
                {
                    exercise = new Exercise
                    {
                        Name = spec.Name,
                        Description = SeedNote,
                        Muscle = spec.Muscle,
                        SpecificMuscleGroups = string.Join(", ", spec.Muscles.Select(x => x.Muscle)),
                        Equipment = spec.Equipment,
                        Category = "Strength",
                        EquipmentType = spec.Equipment,
                        IsBodyweight = spec.IsBodyweight,
                        IsIsolation = spec.IsIsolation,
                        IsCompound = !spec.IsIsolation,
                        DefaultProgressionStepKg = spec.ProgressionStepKg,
                        UserId = userId
                    };

                    exercise.ExerciseMuscles = BuildExerciseMuscles(exercise.Id, spec.Muscles);
                    _db.Exercises.Add(exercise);
                    byName[spec.Name] = exercise;
                    continue;
                }

                exercise.Description = SeedNote;
                exercise.Muscle = spec.Muscle;
                exercise.SpecificMuscleGroups = string.Join(", ", spec.Muscles.Select(x => x.Muscle));
                exercise.Equipment = spec.Equipment;
                exercise.Category = "Strength";
                exercise.EquipmentType = spec.Equipment;
                exercise.IsBodyweight = spec.IsBodyweight;
                exercise.IsIsolation = spec.IsIsolation;
                exercise.IsCompound = !spec.IsIsolation;
                exercise.DefaultProgressionStepKg = spec.ProgressionStepKg;

                exercise.ExerciseMuscles.Clear();
                foreach (var muscle in BuildExerciseMuscles(exercise.Id, spec.Muscles))
                {
                    exercise.ExerciseMuscles.Add(muscle);
                }
            }

            await _db.SaveChangesAsync(ct);
            return byName;
        }

        private static List<ExerciseMuscle> BuildExerciseMuscles(
            Guid exerciseId,
            IReadOnlyList<MuscleSpec> muscles)
        {
            return muscles
                .Select(x => new ExerciseMuscle
                {
                    ExerciseId = exerciseId,
                    Muscle = x.Muscle,
                    Role = x.Role,
                    Contribution = x.Contribution
                })
                .ToList();
        }

        private static List<FoodLog> BuildFoodLogs(
            string userId,
            DateTime fromDay,
            DateTime toDay)
        {
            var meals = new[]
            {
                new MealTemplate("Oatmeal bowl", 520, 36, 70, 14, 7),
                new MealTemplate("Chicken rice bowl", 690, 52, 82, 17, 12),
                new MealTemplate("Skyr, banana and almonds", 360, 32, 42, 8, 15),
                new MealTemplate("Salmon, potatoes and greens", 760, 48, 74, 28, 18)
            };

            var logs = new List<FoodLog>();
            var dayCount = (int)(toDay - fromDay).TotalDays + 1;

            for (var dayIndex = 0; dayIndex < dayCount; dayIndex++)
            {
                var day = fromDay.AddDays(dayIndex);
                var isTrainingDay = day.DayOfWeek != DayOfWeek.Sunday;
                var dailyAdjustment = isTrainingDay ? 1.04 : 0.94;
                var wave = Math.Sin(dayIndex * 0.75) * 0.04;

                for (var mealIndex = 0; mealIndex < meals.Length; mealIndex++)
                {
                    var meal = meals[mealIndex];
                    var factor = dailyAdjustment + wave + (mealIndex == 3 ? 0.03 : 0);
                    logs.Add(new FoodLog
                    {
                        UserId = userId,
                        Title = meal.Title,
                        Calories = ScaleInt(meal.Calories, factor),
                        Proteins = ScaleInt(meal.Proteins, factor),
                        Carbs = ScaleInt(meal.Carbs, factor),
                        Fats = ScaleInt(meal.Fats, factor),
                        TimestampUtc = day.AddHours(meal.HourUtc).AddMinutes((dayIndex % 4) * 7),
                        SourceType = SeedSourceType,
                        SourceServings = 1m
                    });
                }
            }

            return logs;
        }

        private async Task<int> UpsertWeightLogsAsync(
            string userId,
            DateTime fromDay,
            DateTime toDay,
            CancellationToken ct)
        {
            var existing = await _db.WeightLogs
                .Where(x =>
                    x.UserId == userId &&
                    x.TimestampUtc >= fromDay &&
                    x.TimestampUtc < toDay.AddDays(1))
                .ToListAsync(ct);

            var byDay = existing
                .GroupBy(x => x.TimestampUtc.Date)
                .ToDictionary(x => x.Key, x => x.First());

            var dayCount = (int)(toDay - fromDay).TotalDays + 1;

            for (var dayIndex = 0; dayIndex < dayCount; dayIndex++)
            {
                var day = fromDay.AddDays(dayIndex);
                var trend = 86.4 - (dayIndex * 0.035);
                var noise = Math.Sin(dayIndex * 1.7) * 0.18 + Math.Cos(dayIndex * 0.41) * 0.07;
                var weightKg = Math.Round(trend + noise, 1, MidpointRounding.AwayFromZero);
                var timestamp = day.AddHours(6).AddMinutes(20 + dayIndex % 11);

                if (byDay.TryGetValue(day, out var existingLog))
                {
                    existingLog.WeightKg = weightKg;
                    existingLog.TimestampUtc = timestamp;
                    continue;
                }

                _db.WeightLogs.Add(new WeightLog
                {
                    UserId = userId,
                    WeightKg = weightKg,
                    TimestampUtc = timestamp
                });
            }

            return dayCount;
        }

        private static List<WorkoutSession> BuildWorkoutSessions(
            string userId,
            DateTime trainingFrom,
            IReadOnlyDictionary<string, Exercise> exercises)
        {
            var sessions = new List<WorkoutSession>();
            var counts = new Dictionary<SplitType, int>
            {
                [SplitType.Push] = 0,
                [SplitType.Pull] = 0,
                [SplitType.Legs] = 0
            };

            for (var dayOffset = 0; counts.Values.Any(x => x < 10); dayOffset++)
            {
                var cycleDay = dayOffset % 7;
                if (cycleDay == 6) continue;

                var split = cycleDay switch
                {
                    0 or 3 => SplitType.Push,
                    1 or 4 => SplitType.Pull,
                    _ => SplitType.Legs
                };

                if (counts[split] >= 10) continue;

                var occurrence = counts[split];
                counts[split]++;
                var startedAt = trainingFrom
                    .AddDays(dayOffset)
                    .AddHours(16)
                    .AddMinutes(25 + (occurrence % 4) * 8);

                sessions.Add(BuildWorkoutSession(
                    userId,
                    split,
                    occurrence,
                    startedAt,
                    exercises));
            }

            return sessions;
        }

        private static WorkoutSession BuildWorkoutSession(
            string userId,
            SplitType split,
            int occurrence,
            DateTime startedAt,
            IReadOnlyDictionary<string, Exercise> exercises)
        {
            var plans = WorkoutPlans(split);
            var session = new WorkoutSession
            {
                UserId = userId,
                ClientRequestId = $"{SeedSessionPrefix}{split.ToString().ToLowerInvariant()}-{occurrence + 1:D2}",
                StartedAtUtc = startedAt,
                FinishedAtUtc = startedAt.AddMinutes(62 + (occurrence % 5) * 4),
                Title = $"{split} #{occurrence + 1}",
                Notes = SeedNote
            };

            for (var exerciseIndex = 0; exerciseIndex < plans.Count; exerciseIndex++)
            {
                var plan = plans[exerciseIndex];
                var exerciseLog = new WorkoutExerciseLog
                {
                    ExerciseId = exercises[plan.ExerciseName].Id,
                    Order = exerciseIndex + 1
                };

                for (var setIndex = 0; setIndex < plan.Sets; setIndex++)
                {
                    var weight = RoundToNearest(
                        plan.StartWeightKg + occurrence * plan.ProgressionKg - setIndex * plan.BackoffKg,
                        2.5);
                    var reps = Math.Max(5, plan.TargetReps - ((occurrence + setIndex) % 2));

                    exerciseLog.Sets.Add(new SetLog
                    {
                        SetNumber = setIndex + 1,
                        WeightKg = weight,
                        Reps = reps,
                        Rir = Math.Round(1.5 + ((occurrence + setIndex) % 4) * 0.5, 1),
                        SetType = setIndex == 0 ? "top" : "backoff"
                    });
                }

                session.ExerciseLogs.Add(exerciseLog);
            }

            RecalculateTotals(session);
            return session;
        }

        private static void RecalculateTotals(WorkoutSession session)
        {
            var sets = session.ExerciseLogs.SelectMany(x => x.Sets).ToList();
            session.TotalSets = sets.Count;
            session.TotalReps = sets.Where(x => x.Reps.HasValue).Sum(x => x.Reps!.Value);
            session.TotalVolume = sets
                .Where(x => x.WeightKg.HasValue && x.Reps.HasValue)
                .Sum(x => x.WeightKg!.Value * x.Reps!.Value);
        }

        private static int ScaleInt(int value, double factor)
        {
            return Math.Max(0, (int)Math.Round(value * factor, MidpointRounding.AwayFromZero));
        }

        private static double RoundToNearest(double value, double step)
        {
            return Math.Round(value / step, MidpointRounding.AwayFromZero) * step;
        }

        private static IReadOnlyList<ExerciseSpec> ExerciseSpecs()
        {
            return
            [
                new ExerciseSpec(
                    "Mock Bench Press",
                    "Bryst",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Bryst", MuscleRole.Primary, 1m), new("Triceps", MuscleRole.Secondary, 0.45m), new("Fremre skulder", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Incline DB Press",
                    "Bryst",
                    "Dumbbell",
                    false,
                    false,
                    2.5m,
                    [new("Bryst", MuscleRole.Primary, 1m), new("Fremre skulder", MuscleRole.Secondary, 0.55m), new("Triceps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Overhead Press",
                    "Skuldre",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Fremre skulder", MuscleRole.Primary, 1m), new("Sideskulder", MuscleRole.Secondary, 0.45m), new("Triceps", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Lateral Raise",
                    "Skuldre",
                    "Dumbbell",
                    false,
                    true,
                    1m,
                    [new("Sideskulder", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Triceps Pushdown",
                    "Armer",
                    "Cable",
                    false,
                    true,
                    2.5m,
                    [new("Triceps", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Deadlift",
                    "Rygg",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.65m), new("Nedre rygg", MuscleRole.Secondary, 0.55m), new("Traps", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Pull-up",
                    "Rygg",
                    "Bodyweight",
                    true,
                    false,
                    1.25m,
                    [new("Lats", MuscleRole.Primary, 1m), new("Biceps", MuscleRole.Secondary, 0.55m), new("Traps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Barbell Row",
                    "Rygg",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Lats", MuscleRole.Primary, 1m), new("Traps", MuscleRole.Secondary, 0.5m), new("Biceps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Face Pull",
                    "Skuldre",
                    "Cable",
                    false,
                    true,
                    2.5m,
                    [new("Bakre skulder", MuscleRole.Primary, 1m), new("Traps", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Hammer Curl",
                    "Armer",
                    "Dumbbell",
                    false,
                    true,
                    1m,
                    [new("Biceps", MuscleRole.Primary, 1m), new("Brachialis", MuscleRole.Secondary, 0.6m)]),
                new ExerciseSpec(
                    "Mock Squat",
                    "Bein",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Quadriceps", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.65m), new("Hamstrings", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Romanian Deadlift",
                    "Bein",
                    "Barbell",
                    false,
                    false,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.7m), new("Nedre rygg", MuscleRole.Secondary, 0.35m)]),
                new ExerciseSpec(
                    "Mock Leg Press",
                    "Bein",
                    "Machine",
                    false,
                    false,
                    5m,
                    [new("Quadriceps", MuscleRole.Primary, 1m), new("Rumpe", MuscleRole.Secondary, 0.45m)]),
                new ExerciseSpec(
                    "Mock Leg Curl",
                    "Bein",
                    "Machine",
                    false,
                    true,
                    2.5m,
                    [new("Hamstrings", MuscleRole.Primary, 1m)]),
                new ExerciseSpec(
                    "Mock Standing Calf Raise",
                    "Bein",
                    "Machine",
                    false,
                    true,
                    5m,
                    [new("Bakside legg", MuscleRole.Primary, 1m)])
            ];
        }

        private static IReadOnlyList<WorkoutExercisePlan> WorkoutPlans(SplitType split)
        {
            return split switch
            {
                SplitType.Push =>
                [
                    new("Mock Bench Press", 4, 8, 82.5, 1.5, 2.5),
                    new("Mock Incline DB Press", 3, 10, 32.5, 0.75, 1.25),
                    new("Mock Overhead Press", 3, 8, 50, 1.0, 2.5),
                    new("Mock Lateral Raise", 3, 14, 12.5, 0.25, 0.5),
                    new("Mock Triceps Pushdown", 3, 12, 32.5, 0.75, 1.25)
                ],
                SplitType.Pull =>
                [
                    new("Mock Deadlift", 3, 5, 130, 2.0, 5),
                    new("Mock Pull-up", 4, 8, 5, 0.75, 1.25),
                    new("Mock Barbell Row", 3, 9, 75, 1.5, 2.5),
                    new("Mock Face Pull", 3, 14, 27.5, 0.5, 1.25),
                    new("Mock Hammer Curl", 3, 11, 17.5, 0.5, 1.0)
                ],
                _ =>
                [
                    new("Mock Squat", 4, 7, 105, 1.75, 2.5),
                    new("Mock Romanian Deadlift", 3, 8, 95, 1.5, 2.5),
                    new("Mock Leg Press", 3, 12, 170, 3.0, 5),
                    new("Mock Leg Curl", 3, 12, 47.5, 1.0, 2.5),
                    new("Mock Standing Calf Raise", 4, 13, 85, 2.0, 5)
                ]
            };
        }

        private enum SplitType
        {
            Push,
            Pull,
            Legs
        }

        private sealed record MealTemplate(
            string Title,
            int Calories,
            int Proteins,
            int Carbs,
            int Fats,
            int HourUtc);

        private sealed record MuscleSpec(
            string Muscle,
            MuscleRole Role,
            decimal Contribution);

        private sealed record ExerciseSpec(
            string Name,
            string Muscle,
            string Equipment,
            bool IsBodyweight,
            bool IsIsolation,
            decimal ProgressionStepKg,
            IReadOnlyList<MuscleSpec> Muscles);

        private sealed record WorkoutExercisePlan(
            string ExerciseName,
            int Sets,
            int TargetReps,
            double StartWeightKg,
            double ProgressionKg,
            double BackoffKg);
    }
}
